name: models
description: A package that exposes reusable models for Compass modules.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
