name: very_good_coffee
publish_to: none

environment:
  sdk: ^3.7.0

workspace:
    - packages/coffee_repository
    - packages/dart_envs
    - packages/http_client
    - packages/local_coffee
    - packages/models
    - packages/app

dependencies:
  equatable: ^2.0.7
  logging: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.14
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
