import 'dart:ui';

extension StringExtension on String {
  /// Generates a [Color] from a [String].
  /// The [Color] is generated by hashing the [String] and using the hash as the RGB value.
  /// The [opacity] parameter can be used to set the opacity of the [Color].
  /// The [opacity] must be between 0.0 and 1.0.
  /// The default value of [opacity] is 1.0.
  ///
  /// Example:
  /// ```dart
  /// final color = 'Hello, World!'.toColor();
  /// ```
  Color toColor({double opacity = 1.0}) {
    assert(
      opacity >= 0.0 && opacity <= 1.0,
      'Opacity must be between 0.0 and 1.0',
    );
    final hash = hashCode;
    final red = (hash & 0xFF0000) >> 16;
    final green = (hash & 0x00FF00) >> 8;
    final blue = hash & 0x0000FF;
    return Color.fromRGBO(red, green, blue, opacity);
  }
}
