name: http_client
description: "An HTTP client for VGC module."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  dart_envs: ^0.0.1
  dio: ^5.8.0+1
  logging: ^1.3.0
  models: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.15
  test: ^1.25.15
  mockito: ^5.4.5

