arb-dir: lib/presentation/l10n/arb
output-dir: lib/presentation/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
format: true
nullable-getter: false
synthetic-package: false
