name: app
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  coffee_repository: ^0.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  http_client: ^0.0.1
  intl: ^0.19.0
  local_coffee: ^0.0.1
  models: ^0.1.0
  sensors_plus: ^6.1.1
  shimmer: ^3.0.0
resolution: workspace

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true
